# Eenvoudige samenvatting met belangrijkste zinnen
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lsa import LsaSummarizer
import nltk

nltk.download('punkt_tab')
tekst = """
Operatie Rode Draak is een van de bekendste missies van de Belgische Defensie. Twee militairen lieten het leven bij de missie, een derde bij de vervolgmissie Zwarte Draak.

Juli 1964. De voormalige Belgische kolonie Congo gaat door een woelige periode. Vrijwel meteen na de onafhankelijkheid in 1960 breken onlusten uit. Een deel van het leger muitte, de provincies Katanga en Zuid-Kasaï scheidden zich met Belgische steun af (België had er immers grote industriële belangen). De VN-vredestroepen arriveerden in het land, nadat de VN-Veiligheidsraad in resolutie 143 België opriep om al haar soldaten terug te trekken en te laten vervangen door VN-vredestroepen, die zouden instaan voor het terugbrengen en bewaren van de vrede.

Er heerste echter al snel onenigheid over de taak: Lumumba wilde dat de VN de afvallige provincies zou veroveren voor Congo; zijn eigen Force Publique (het leger van Congo) was namelijk in brokken uiteengevallen. VN-secretaris-generaal Dag Hammarskjöld weigerde, waarop Lumumba zijn toevlucht zocht bij de Sovjet-Unie.

Een jaar later lag de situatie helemaal anders. Lumumba was geëxecuteerd in opdracht van zijn belangrijkste militair adviseur, Joseph-Désiré Mobutu, die een staatsgreep pleegde en de Sovjetadviseurs buitenkegelde. Die boden op hun beurt hun diensten aan de Vrije Republiek Congo, een rivaliserende regering. Congo-Leopoldstad, de regering-Mobutu, kreeg na de dood van VN-secretaris-generaal Dag Hammarskjöld, ten gevolge van een vliegtuigongeluk, wel de steun van VN-troepen. Samen met de VN slaagde Congo-Leopoldstad erin de afvallige provincies te heroveren.

Rebellie in het oosten
In 1964 breekt een volgende ‘aflevering’ uit: in het westelijke district Kwilu komt Pierre Mulélé begin van dat jaar in opstand. De Armée Nationale Congolaise (ANC) slaagt erin deze in de kiem te smoren, maar gaan bijzonder brutaal te werk, met talloze oorlogsmisdaden tot gevolg. Daarop rebelleren de Simba, een groep stammen uit het oosten van het land onder leiding van de marxistische Comité National de Libération. De Simba-beweging begint bij Albertstad (het huidige Kalemie), aan het Tanganyikameer, en rukt op richting het noorden. Onderweg wint de beweging aan rekruten, binnen enkele weken wordt Kindu veroverd en rukken de rebellen op richting Stanleystad.

In grote delen van het noordoosten van Congo, veroverd door de Simba, vinden gruwelijkheden plaats. De jeunesse, bendes jongeren die elke aanval tegen de regering steunden, bleken niet in de hand te houden; duizenden mensen werden vermoord, honderden westerlingen werden gegijzeld. Echt georganiseerd vechten de Simba echter niet: toverdokters maakten hen wijs dat ze in leeuwen zouden veranderen in de strijd en onkwetsbaar waren voor kogels. Ze mogen zeker niet naar links of rechts kijken, zo wil de overlevering, of hun toverdrank, de ‘dawa’, werkte niet. In het begin vochten ze met handwapens, speren en zwaarden, maar naarmate het offensief aan kracht won, rustten ze zich uit met in beslag genomen vuurwapens, en begon er ook een zekere militaire structuur te bestaan.


In blauw: gebied in handen van de regering
In rood: gebied in handen van de Simbarebellen
In bruin: gebied in handen van de rebellen van Pierre Mulélé
De situatie zorgde voor grote onrust bij de Congolese overheid: het ANC beschikte namelijk niet over de middelen of organisatie om dit rebellenleger aan te pakken. De Belgische terugtrekking na de onafhankelijkheid in 1960 zorgde ervoor dat zo goed als alle ervaren (onder)officieren uit de Force Publique ofwel naar België terugkeerden, of heil zochten bij het Katanga van Moise Tshombe. Bij gevolg beschikte het ANC amper over ervaren officieren om het leger te leiden, laat staan om grote opdrachten of missies te plannen.

Steun van bondgenoten
Ook bij haar bondgenoten, de Verenigde Staten en België, was men ongerust over de situatie. Beide landen hadden namelijk nog grote belangen in het land; zo waren er nog tal van Belgische bedrijven actief, met heel wat blanke Belgische werknemers. Voor de Amerikanen speelde het geopolitieke belang veel meer; de Vietnam- en Koude Oorlog waren volop bezig, en een door de communisten gesteunde rebellenbeweging die de regering omverwerpt in het op één na grootste land van Afrika, dat zouden ze niet tolereren.

De eerste stap was het opschalen van de militaire bijstand. Onder druk van de VS en op vraag van de Congolese regering ging België akkoord met het leveren van piloten en onderhoudspersoneel voor Amerikaanse C-47-transportvliegtuigen en H-21-helikopters, voor transport- en evacuatieopdrachten. Onder de naam FATAC (Force Aérienne Tactique Congolaise) zouden de Belgen echter ook ingezet worden voor verkenningsopdrachten; een C-47 werd zelfs uitgerust met een mitrailleur. Later volgden Amerikaanse T-28-gevechtsvliegtuigen, gevolgen door Cubanen, die door de CIA initieel waren gerekruteerd om deel te nemen aan de (mislukte) Invasie van de Varkensbaai, om Cuba te heroveren van Fidel Castro.

En dan kwam op 10 juli 1964 Moïse Tshombe, ex-president van Katanga, aan de macht als premier van Congo. Hij zag maar één manier om de rebellen klein te krijgen: de militaire. Dat de ANC weinig zou verwezenlijken wist hij, dus haalde hij zijn Katangese gendarmes terug, dik tegen de zin van generaal Mobutu, de opperbevelhebber van de ANC. De Katangese gendarmes waren na de overgave van Katanga naar buurland Angola gevlucht. Alleen, ze waren slecht geleid; de blanke officieren die tijdens de Katangese onafhankelijkheid beschikbaar waren, ontbraken nu. Een integratie binnen de ANC was onmogelijk (de gendarmes weigerden ANC-bevelen op te volgen, en spraken Swahili, terwijl de voertaal van de ANC Lingala was).

Tshombe polste bij de bondgenoten België en de VS, of die geen bijstand wilden leveren aan de gendarmes. Dat stootte op een ‘njet’ van Spaak, die vreesde dat Belgische inmenging forse gevolgen zou hebben voor de Belgische gegijzelden in Simba-gebied. Die ‘njet’ werd echter relatief toen ook Stanleyville in handen van de rebellen viel: Spaak zag maar één oplossing: onder de tafel toch militaire bijstand leveren. De spilfiguur in dit verhaal is kolonel Frédéric Vandewalle, een Belgische militair die eerder bij de Force Publique diende, nadien hoofd van de staatsveiligheid werd in de kolonie, en mee de Katangese secessie organiseerde. Het was Tshombe zelf die in een brief aan Spaak vroeg om Vandewalle naar Congo te mogen halen als zijn persoonlijke militaire raadgever.


Kolonel Vandewalle – Bron: Compagnons Ommegang
Eens in Congo ging Vandewalle aan het tekenen. Hij werkte een strategie uit om met gemengde colonnes, bestaande uit Katangese gendarmes en blanke huurlingen, onder bevel van Belgische officieren, het rebellengebied te heroveren. Gezien de gevoeligheid omtrent Belgische militairen in Congo, noemde hij ze de ‘logistieke ploegen’, maar in werkelijkheid hadden ze ook het bevel over de verschillende colonnes. De uitvalsbasis zou Kamina worden, waar een voormalige Belgische basis lag van de paracommando’s, en vanwaar de FATAC ook al opereerde. Tshombe ging hiermee akkoord, de Amerikanen waren ook verheugd. Spaak bond uiteindelijk ook in, maar zweeg hierover naar buiten toe.

Gedurende die periode kwam de ‘realpolitiker’ in Spaak naar boven: achter de schermen onderhandelde hij met Christophe Gbenye, leider van de Simbarebellie, die op kosten van Buitenlandse Zaken in Brussel werd uitgenodigd. In die gesprekken stelde hij dat een militaire oplossing uitgesloten was. Nadien verzamelde Spaak ook nog de diplomatieke vertegenwoordigers van de Afrikaanse landen, waar hij het volgende verklaarde: “Ik kan u zeggen, maar dat moet u voor zich houden, dat ze (de Amerikanen, red.) me werkelijk hebben gevraagd of België niet bereid was tot een militaire operatie. (…) Ik geloof niet in een militaire oplossing voor Congo.” De brief met toestemming om Belgische militairen aan het hoofd te zetten van Vandewalle’s heroveringscolonnes was toen al de deur uit.

Rekruteren in Brussel
Ook nadien bleef Spaak die enigszins hypocriete houding volhouden. In de zoektocht naar huurlingen voor de colonnes van Vandewalle (officieel de 5e Gemechaniseerde Brigade), deden Tshombe en Vandewalle beroep op Jerry Puren en Mike Hoare, twee huurlingen die ook al tijdens de Katangese secessie actief ronselden. In het Zuid-Afrikaanse Johannesburg kwam een rekruteringscentrum, en de Zuid-Afrikaanse regering gaf militairen zelfs toestemming om tot zes maanden als huurling in Congo te gaan vechten. De VS en België vreesden dat de terugkeer van Zuid-Afrikaanse huurlingen naar Congo (zoals al het geval was bij de Katangese secessie) de overige Afrikaanse landen tegen de borst zou stoten en hen doen herinneren aan slechtere tijden. In ruil hiervoor kneep Spaak een oogje dicht toen de Congolees militair attaché in Brussel majoor Jérôme Babia, samen met de Belgische majoor Charles Bertrand, een rekruteringscentrum openden in Brussel. In burgerkleding vertrokken ze vanop Zaventem naar Congo; toen de politie hier lucht van kreeg en op Zaventem ging controleren, weken ze uit via Parijs. Spaak wist hiervan, maar greep niet verder in.

Vandewalle had zijn huurlingen echter niet in de hand: “Ze zijn allen schuldig aan ernstige excessen waarvan de bevolking het slachtoffer is, zoals overvallen, verkrachtingen moord en afranseling”, stelde een CIA-verslag. “Een losgeslagen bende macho’s die vinden dat plunderen en brandkasten kraken deel uitmaken van hun prerogatieven”, zei de Amerikaans ambassadeur in Congo, George McMurtrie Godley. Maar het offensief tegen de Simba was wel een succes: met behulp van achtergelaten VN-voertuigen (de Zweedse Scania Vabis, ook wel ‘badkuip’ genoemd), een eenzame Brits Ferret-verkenningsvoertuig en een samenraapsel van jeeps en vrachtwagens, ondersteund door transport via trein of Amerikaanse C-130-vliegtuigen, en uitgerust met Belgische bewapening en munitie, rukten ze op richting de grote steden die door de Simba-rebellen waren veroverd.

Ondertussen nam in Brussel de vrees toe dat deze opmars de Simba tot het uiterste zou drijven, waarop ze blanke gijzelaars zouden doden. Zeker in Stanleyville (525 Belgen), maar ook in Paulis, Watsa en Bunia bevonden zich nog veel Belgische gegijzelden. Spaak zag hier maar één oplossing voor: de gijzelaars manu militari bevrijden, in eerste instantie uit Stanleyville. Hij wou deze ‘humanitaire reddingsoperatie’, zoals hij het noemde, niet laten uitvoeren door de troepen van Vandewalle; Spaak vreesde dat dit kon geïnterpreteerd worden als directe steun aan Tshombe en een daad van neokolonialisme. Spaak gaf de voorkeur aan een paraoperatie; België zou de para’s leveren, de VS de vliegtuigen.

Op 11 november 1964 stapten de Amerikaanse brigadegeneraal Russell Dougherty en een team planners het ministerie van Landsverdediging in de Wetstraat nr. 2 binnen. Ook aanwezig: kolonel Robert Louvigny, vertegenwoordiger van de generale staf, en kolonel Charles Laurent, bevelhebber van het regiment paracommando, die zelf de leiding zou nemen over de missie. Na enkele dagen discussiëren kwamen het plan tot stand dat nadien operatie Rode Draak zou gaan heten. Enkele dagen later ging de operatie van start.


Kolonel Laurent – Bron: Compagnons Ommegang
Op 17 november zetten 12 Amerikaanse C-130’s koers vanuit het Franse Évreux, destijds een vooruitgeschoven basis van de Amerikaanse Luchtmacht in Europa (USAFE), naar Kleine Brogel om alles en iedereen in te laden. Onder het mom van deelname aan een gezamenlijke NAVO-oefening in Turkije, werden 545 paracommando’s, afkomstig van het 1e Para in Dienst en het 2e Commando in Flawinne, ingescheept, richting het Britse eiland Ascension. Zo moest geen toestemming worden gevraagd aan andere Afrikaanse landen om door hun luchtgebied te vliegen, wat er mee voor zorgde dat de missie geheim kon blijven. De militairen kregen een enveloppe toegestopt, die ze pas na opstijgen op Kleine Brogel mochten openen. Daarin stond wat ze echt zouden gaan doen.

Vier draken
Achter de schermen werd volop doorgewerkt. In Brussel gingen de Belgen en Amerikanen opnieuw aan het plannen voor eventuele vervolgoperaties op Bunia (Witte Draak), Paulis (Zwarte Draak) en Watsa (Groene Draak), met telkens 48 uur tijd tussen. Het Amerikaanse ministerie van Buitenlandse Zaken probeerde ondertussen via bemiddeling toch een diplomatieke oplossing voor het conflict te bekomen. Het doel was echter vooral om de rebellen aan de onderhandelingstafel te houden, om de executie van gijzelaars (zoals de Amerikaanse missionaris Paul Carlson) uit te stellen en de colonnes van Vandewalle de kans te geven om zelf de gijzelaars in Stanleyville te ontzetten.

Spaak zag het anders; op 20 november verklaarde hij op een persconferentie dat Belgische para’s met Amerikaanse vliegtuigen naar Ascension waren gebracht. Hij wou bekomen dat de VS akkoord gingen met het overbrengen van de para’s naar Kamina, van waaruit de operatie op Stanleyville werd georganiseerd. Als de VS dit nu zouden weigeren en Amerikaanse burgers stierven door rebellengeweld, waren de gevolgen groot voor president Johnson. Zaterdag 21 november kwam de toestemming, de para’s mochten naar Kamina. Pas toen de C-130’s al boven Congo vlogen, kreeg de Congolese regering de documenten voorgeschoteld die het moest tekenen, en waarin de goedkeuring van de operatie werd vastgelegd. Een sterk staaltje diplomatie van Spaak.

In Kamina kregen de para’s nog wat training (ze hadden immers nog nooit uit een C-130 gesprongen), en gingen de toplui opnieuw rond de tafel. Dit keer was er discussie over de coördinatie met L’Ommegang, de colonnes van Vandewalle: zouden deze gelijktijdig Stanleyville bereiken, of wie zou anders het eerste initiatief krijgen? Uiteindelijk werd gekozen voor een gelijktijdige aankomst; dinsdag 24 november, om 6u ’s ochtends, zouden para’s boven Stanleyville springen. De avond voordien, om 23u, stuurden de VS het codewoord ‘Big’ naar Kamina. De Belgische ‘Punch volgde’: Rode Draak kreeg groen licht.


Om 3u stegen de eerste vijf C-130’s, met daarin 320 para’s van het 1e Bataljon Para, op. Hun missie was om te springen boven de luchthaven van Stanleyville, ten westen van de stad, en de landingsbaan vrijmaken van de autowrakken en tonnen, door de Simba daar geplaatst als versperring. Om 6u stipt sprongen ze uit de zijdeuren van de C-130’s, op 210 meter hoogte. Het Simba-vuur was zeer onnauwkeurig, en slechts drie para’s liepen verwondingen op door slecht neer te komen. De weerstand werd uitgeschakeld, de landingsbaan vrijgemaakt. Kolonel Laurent richtte de verkeerscontroletoren in tot commandopost, en 45 minuten later konden de overige zeven C-130’s landen. Hierin zaten de voertuigen, gepantserde jeeps en FN AS 24-driewielers, 128 commando’s van het 2e Commando en extra materiaal. Het 12e toestel was ingericht als hospitaal.

Met de eerste stap succesvol afgerond, startten de para’s aan stap 2: het zoeken en bevrijden van gijzelaars. Aangezien kolonel Laurent over drie compagnieën beschikte, liet hij elk van hen een andere richting uit gaan: de 11e compagnie deed het centrum, met de gevangenis en de hotels Victoria en Congo Palace; de 13e Compagnie trok door het zuiden van de stad, via de kathedraal, naar het militaire kamp Sergeant Ketele, in het oosten van de stad; en de 12e Compagnie ging noordwaarts, om de flanken te beveiligen en vluchtwegen af te sluiten.

In het centrum kwamen de para’s al snel een groep Simba-rebellen tegen, die gijzelaars gebruikten als menselijk schild en richting het vliegveld trokken. De Simba’s openden het vuur, 22 gijzelaars, waaronder 20 Belgen, stierven, 40 anderen raakten gewond. De overlevenden werden richting het vliegveld gebracht, vanwaar de C-130’s af en aan vlogen om gijzelaars in veiligheid te brengen. Steeds meer blanken, maar ook Congolezen, zochten toevlucht tot het vliegveld, in de hoop weg te geraken van de rebellen.

Om 10:30 arriveerde de colonne van kolonel Vandewalle bij kamp Sergeant Ketele. De kolonel zelf reed door naar Laurent, beide heren besloten dat L’Ommegang zich verder op de stad zou concentreren, de para’s bleven links van het Kitengekanaal, en zouden de evacuaties naar het vliegveld verder begeleiden.


"""

parser = PlaintextParser.from_string(tekst, Tokenizer("dutch"))
summarizer = LsaSummarizer()
samenvatting = summarizer(parser.document, 3)  # 3 belangrijkste zinnen

for zin in samenvatting:
    print(zin)

